# -*- coding: utf-8 -*-
"""Sala de espera.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G5mJcyBbD2XEtHgbIa0QHndDj85pjJDX
"""

import streamlit as st
from datetime import datetime, timedelta

# Configuración inicial
st.set_page_config(page_title="Sala de Espera de Zoom", layout="centered")
st.title("Sala de Espera para Reunión en Zoom")

# Configura la hora de la reunión
meeting_time_str = "2024-10-26 20:00:00"  # Reemplaza con la fecha y hora de tu reunión
meeting_time = datetime.strptime(meeting_time_str, "%Y-%m-%d %H:%M:%S")

# Función para calcular el tiempo restante
def get_time_remaining():
    now = datetime.now()
    return meeting_time - now

# Muestra un mensaje de bienvenida
st.write("Bienvenido a la sala de espera de la reunión en Zoom.")
st.write("La reunión comenzará en la siguiente fecha y hora:")
st.write(meeting_time.strftime("%d %B %Y, %H:%M:%S"))

# Calcula el tiempo restante y muestra un temporizador
time_remaining = get_time_remaining()

if time_remaining.total_seconds() > 0:
    days, seconds = time_remaining.days, time_remaining.seconds
    hours = seconds // 3600
    minutes = (seconds % 3600) // 60
    seconds = seconds % 60
    st.write(f"Tiempo restante: {days} días, {hours} horas, {minutes} minutos, {seconds} segundos")
else:
    st.write("La reunión ha comenzado. Puedes unirte ahora.")

# Botón para redirigir a la reunión en Zoom cuando sea la hora
if time_remaining.total_seconds() <= 0:
    meeting_link = "https://us06web.zoom.us/j/89759931852?pwd=WPooqQxvsh5wEZ1GKebxp9Vs8ux5bw.1"  # Coloca aquí el enlace de Zoom
    st.markdown(f"[Unirse a la reunión en Zoom]({meeting_link})", unsafe_allow_html=True)
else:
    st.write("Por favor, espera hasta que sea la hora de la reunión.")